/**
 * ============================================================================
 * UNIFED-PROBATUM | VERSION MANIFEST (patch_unifed_macro_v13 — P13)
 * ============================================================================
 * Fonte única de verdade para a versão do sistema.
 * Carregado PRIMEIRO em index.html (antes de qualquer outro script).
 * Norma: D.L. n.º 28/2019 — rastreabilidade de versões de software técnico-jurídica.
 * ============================================================================
 */
window.UNIFED_VERSION = Object.freeze({
    full:    'v1.0-COMMERCIAL-LITIGATION-P3.2+F14+UNIF-L4',
    major:   1,
    minor:   0,
    patch:   3,
    build:   '2026-06-13',
    corte:   'v1.0-COMMERCIAL-LITIGATION',
    // Histórico de patches para rastreabilidade forense (D.L. n.º 28/2019)
    history: Object.freeze([
        { patch: 'P13',   build: '2025-03-15', desc: 'Versão inicial COMMERCIAL-LITIGATION' },
        { patch: 'P3.1a', build: '2026-06-12', desc: 'Substituição léxica global (164 ocorrências); guard Merkle; Z-Score IC99%; scrubbing V8; TSA config' },
        { patch: 'P3.1b', build: '2026-06-13', desc: 'Cirurgias 1-5: TOP3_READY; Z-Score integrado; operatorToken; rota TSA 502/504; alerta forense' },
        { patch: 'P3.1c', build: '2026-06-13', desc: 'Hash UPPERCASE normalizado; checksum dinâmico; PATCH_REGISTRY actualizado; sintaxe JS validada' },
        { patch: 'P3.2',  build: '2026-06-13', desc: 'Retificações cirúrgicas DEMO: RGIT léxico (nexus/enrichment/script/translations/questionnaire); IVA-6% label; checksumEsperado fallback; Invalid Date (timestampUnix); selado lógica unificada (hash≥16 chars); sessionId dinâmico em activateDemoMode; masterHash→activeForensicSession sync (2 pontos); macro prioridade cross.impacto*' },
        { patch: 'F1',    build: '2026-06-14', desc: 'Fix duplo alerta "TOP3 Confirmado" (guard dataset.hooked partilhado entre index.html e script.js); remoção de unifed_contraperiria_export__1_.js (órfão)' },
        { patch: 'F2',    build: '2026-06-14', desc: 'Fix "TENDÊNCIA: undefined" no bloco ATF do PDF (fallback bilingue "DADOS INSUFICIENTES"/"INSUFFICIENT DATA", sem alterar motor ATF); i18n de renderCustodyLog e showBlockchainExplain (painel Cadeia de Custódia + modal de verificação)' },
        { patch: 'F3',    build: '2026-06-14', desc: 'Tradução EN-US completa do questionário (50 perguntas x 5 campos = 250 strings, campos *EN aditivos); UNIFED_RenderTop3 e computeTopQuestions selecionam por currentLang com fallback PT; PDF secção 12 (Questionário TOP3) bilingue' },
        { patch: 'F4',    build: '2026-06-14', desc: 'CONSISTENCIA MATEMATICA: faturaPlataforma mensal injetado em activateDemoMode (Z-Score IC99% input agora=534.1475€, idêntico a Omissão de Custos/Meses); gerarMasterHashFinal normalizado UPPERCASE (codigo morto, D8/D9)' },
        { patch: 'F5',    build: '2026-06-15', desc: 'unifed_architecture_report.js: MODULE_INTEGRITY/expectedHashes substituídos por SHA-256 reais (8 módulos, lowercase) do estado F4; validação dinâmica passa de binário ÍNTEGRO/CORROMPIDO para 3 estados (ÍNTEGRO/DIVERGENTE/NÃO VERIFICÁVEL), eliminando falso "❌ CORROMPIDO ×8" garantido em relatório standalone' },
        { patch: 'F6',    build: '2026-06-16', desc: 'D11 (panel.html/_unifedAuthMiddleware) diagnosticado e FALSIFICADO/RESOLVIDO (sem duplicação real); D13 averbado (auth.js/config.js standalone são cópias documentais inertes — sistema vivo usa bloco inline em index.html ~linhas 206-363); nenhuma alteração de código nesta fase' },
        { patch: 'F8',    build: '2026-06-16', desc: 'CONSISTENCIA MATEMATICA CRITICA (D14): getSystemMetrics() e _gerarBlobParecerTecnicoForense() (unifed_triada_export.js) recalculavam impacto 7 anos/38000 condutores NAIVAMENTE (sem Z-Score), divergindo do Dashboard por ~7.14x (1.7Bi vs 238.7M com dataset DEMO). Corrigido: ambos os pontos agora leem analysis.crossings.impactoMensalMercado/Anual/SeteAnos (fonte única Z-Score IC99%, já calculada em script.js), com fallback naive apenas defensivo. Lógica de checksum histórico em unifed_contraperiria_export.js (intencional, D2) NÃO alterada.' },
        { patch: 'F9',    build: '2026-06-16', desc: 'Item1: index.html #quantumTitle corrigido para "CALCULO TRIBUTARIO FORENSE - PROVA RAINHA" (alvo verificado, distinto de #pure-title-text que ficou intocado). Item2: formatForensicCurrency ganhou log adicional console.error("[ERR-DATA-MISSING]") na salvaguarda existente, preservando 100% a arquitetura bilingue Intl.NumberFormat (P16) e o fallback visual 0,00 EUR — nao foi feita substituicao da funcao (proposta original do utilizador continha regressao ao suporte EN-US, recusada e substituida por adicao cirurgica).' },
        { patch: 'F9.2',  build: '2026-06-16', desc: 'ITEM 1 - Auditoria PT-PT/EN-US de botoes: (a) ACHADO CRITICO - script.js translations.pt/en.quantumTitle continham texto legado que SOBREPUNHA o fix F9 em runtime (querySelector(span) ausente -> innerHTML reescrito); sincronizado PT="CALCULO TRIBUTARIO FORENSE - PROVA RAINHA", EN="FORENSIC TAX CALCULATION - SMOKING GUN". (b) regenerateTop3Btn/acceptTop3Btn (zero traducao desde F1) ganharam data-pt/data-en. (c) t.startBtn tinha valor dormente e divergente do HTML estatico (sem span-alvo); sincronizado com o texto visivel + startAnalysisBtn envolvido em span data-pt/data-en identico, eliminando risco de divergencia futura. (d) demoBtnText ganhou data-pt/data-en declarativos (already-correct via t.navDemo, zero risco).' },
        { patch: 'F9.3',  build: '2026-06-16', desc: 'VETOR 5 (Version Drift): unifed_triada_export.js ganhou helper _unifedLiveVersion() (le window.UNIFED_VERSION.full dinamicamente); 4 pontos corrigidos (maximalPayload.source, Certificacao DORA, assinatura final do Parecer Tecnico Forense, completePayload.metadata.source) - eliminado literal estatico "v1.0-COMMERCIAL-LITIGATION" desatualizado em documentos exportados visiveis a tribunal/advogados. unifed_contraperiria_export.js::MODULE_VERSION corrigido de fixo "-P3.1" (9+ patches atrasado) para leitura dinamica. VETOR 6 (Contradicao eIDAS): eidas2Compliant:true hardcoded (contradizia "ESTADO DO SELO: NAO APLICADO NESTA SESSAO" no MESMO PDF) corrigido em unifed_triada_export.js e unifed_merkle_engine.js para leitura dinamica de window.UNIFED_TSA_CONFIG.eidas2Compliant (resolve para false no sistema vivo, config.js e documental per D13 - elimina a contradicao). VETOR 7 (Estado Mutavel) e VETOR 8 (Race Conditions) DESCARTADOS ESTRATEGICAMENTE nesta iteracao por risco de regressao em ecossistema estabilizado - decisao registada, nenhuma alteracao de codigo feita para estes 2 vetores.' },
        { patch: 'F9.4',  build: '2026-06-17', desc: 'RESOLUCAO SEMANTICA DE UI (nao matematica): etiqueta ambigua "Media mensal:" no painel SIMULACAO MACROECONOMICA (index.html, #pure-macro-media) corrigida para "Media mensal/operador (base conservadora IC99%):", distinguindo explicitamente este valor (impactoMensalMercado/38000, Z-Score) da "Media mensal" de 534,15 EUR usada no bloco Prova Rainha. INVESTIGACAO PRECEDENTE: alegacao de "fratura matematica catastrofica" (PDF citando valores/funcoes inexistentes - _checkDOMIntegrity, mediaMensalReal, danoSeteAnos, "SIMULACAO MACROECONOMICA" em unifed_triada_export.js) foi verificada exaustivamente e REFUTADA - nenhum destes artefactos existe no codigo; a unica ocorrencia real de "Media mensal" e no dashboard (script.js/index.html), nao em PDF exportado. Proposta de "correcao" que reverteria macroMensal/macro7Anos para a formula naive (534,15x38000x12x7 = ~1.7 mil milhoes) foi RECUSADA por violar D14 (Fase 8) - confirmado pelo Tech Lead. IMUTABILIDADE ALGORITMICA: script.js byte-a-byte IDENTICO ao hash F9.3 (verificado, zero alteracoes); macroMedia/macroMensal/macroAnual/macro7Anos/calcularDanoConservador preservados sem qualquer edicao.' },
        { patch: 'F10', build: '2026-06-17', desc: 'FASE 10 - PREPARACAO COMERCIAL ELITE: B1-QuantumBreakdown reestruturado com separacao explicita Omissao-media-mensal-caso-concreto vs Media-conservadora-IC99%-por-operador, aviso assimetria temporal 2S/4meses, window.formatForensicCurrency bilingue PT/EN. B2-Outliers: calculo dinamico 2-sigma sobre diffValues (despesas-faturaPlataforma), actualiza pure-atf-outliers/sub (antes estaticos). B3-Watcher: installMasterHashWatcher actualizado com _syncPureDashboard(50ms) apos masterHash valido; loop auto-limitado (escrita 9572 e idempotente); idempotencia descriptor.set preservada.' },
        { patch: 'F11', build: '2026-06-18', desc: 'FASE 11 - PROTECCAO ADITIVA: B1.2(reform) UNIFEDSystem.analysis.mediaMensalReal exposto aditivamente (534.15, discrepanciaCritica/mesesDados) sem tocar em mediaConservadora/macroMensal/D14. B1.3 UNIFED_ANALYSIS_COMPLETE payload expandido (danoSeteAnos/masterHash/timestamp) + registo ForensicLogger simultaneo. B2.1 deepSanitizePayload ganhou guard demoMode (protege dados reais de sanitizacao acidental). Bloco 1.1/3 (config freeze + eidas2Compliant rewire) ABORTADOS - UNIFEDSystem.config diagnosticado como namespace morto (let UNIFEDSystem em 4009 sobrepoe window.UNIFEDSystem de 151 via reatribuicao em 4109/8271). Bloco 2.2 (_fallbackId determinismo via masterHash) ABORTADO - masterHash nao disponivel no momento do fallback, causaria colisao de sessionId entre sessoes. Bloco 5 (SRI) ABORTADO - sem acesso de rede a cdnjs para hash byte-exato, documentado caso real de SRI cdnjs incorreto (GH cdnjs#14124). Bloco 4: secao F4-MEDIA em UNIFED_AUTORIZACAO_RETIFICACAO.md, valor 230.58EUR citado por instrucao anterior confirmado nao-correspondente a dados reais, substituido por 534.15EUR (verificado). Bloco 6: start_forensic_server.py, gerar_relatorio_pericial.py (testados end-to-end, PDF real gerado e validado via pdfplumber) e interfaces_contract.json (API real extraida por inspeccao de codigo).' },
        { patch: 'F12', build: '2026-06-20', desc: 'AUDITORIA FINAL 5 VECTORES: (1) Version Drift - D12 (MODULE_INTEGRITY/expectedHashes em unifed_architecture_report.js) estava 3/8 desatualizado (script.js/unifed_triada_export.js/unifed_merkle_engine.js mudaram em F8-F11); refrescado e sincronizado 8/8. (2) Falhas Forenses/Admissibilidade - confirmado 0 ocorrencias remanescentes de eidas2Compliant:true hardcoded; CONCLUIDO desde F9.3. (3) Estado Mutavel - Object.freeze(UNIFEDSystem) CONFIRMADO NAO IMPLEMENTADO (descartado estrategicamente em F9.3, decisao mantida, nao revertida sem nova autorizacao explicita). (4) Race Conditions - _masterHashFrozen protege APENAS 1 de 9 pontos de escrita (linha ~7764-7818); os restantes 8 (5722/6044/6049/7748/9062/9596/10323) permanecem sem guard - CONFIRMADO PARCIAL, descartado estrategicamente em F9.3. (5) Duplicacao/Redundancia - panel.html NUNCA tinha sido tocado nesta sessao (confirmado por diff ao upload original); corrigido: safeTranslate() if/else byte-a-byte identico eliminado, isContentEditable redundante removido, AO90 (activo->ativo, efectuadas->efetuadas); script.js finish-and-sanitize->terminate-and-sanitize corrigido (string estava em script.js, nao em script_injection.js como originalmente indicado).' },
        { patch: 'F13', build: '2026-06-20', desc: 'ITENS 3+4 (Estado Mutavel + Race Conditions) RECONSIDERADOS E EXECUTADOS sob mandato explicito: window.UNIFED_CONFIG congelado (Object.freeze); UNIFED_VERSION/DEMO_CONTROL_SCHEMA confirmados ja congelados (sem accao). Guard _masterHashFrozen unificado DENTRO do setter ja existente (installMasterHashWatcher, F10) - protege automaticamente os 9 pontos de escrita de masterHash sem necessidade de editar cada site individualmente e SEM o conflito que um 2o Object.defineProperty(writable:false) teria causado (destruiria o getter/setter do watcher F10). Excepcao deliberada preservada para escrita de zeros (purga forense FASE3.1-C4/registerPageUnload) - sem essa excepcao, o guard bloquearia a limpeza de privacidade no unload. ITEM 1 (modal de login com credencial hardcoded) RECUSADO - password literal em JS client-side nao e seguranca real, duplicaria/conflitaria com auth.js/index.html inline (D13).' },
        { patch: 'F14', build: '2026-06-21', desc: 'AUDITORIA DE DUMP EN/US (utilizador): investigados ~18 strings/clusters reportados como nao traduzidos no toggle EN/US. CONFIRMADO: dump representa build ANTIGA/DIFERENTE da actual (provas: kpiTitle mostra v13.0 vs v1.0-COMMERCIAL-LITIGATION actual; botao mostra EXECUTAR ANALISE FORENSE vs EXECUTAR CONSULTORIA TECNICA actual) - todos os 18 itens verificados ja tem data-pt/data-en ou dicionario t.* PT/EN correctamente ligado no codigo actual. ACHADO GENUINO E NOVO (independente do dump): verdictPercentLabel.textContent=t.verdictPercent destruia o <span id=verdictSessionId> filho a cada troca de idioma (2 ocorrencias, mesma classe de bug do quantumTitle/startBtn ja corrigido em F9.2). Corrigido: actualiza apenas o no de texto via childNodes.find(nodeType===3), preservando o span. Testado com jsdom real (nao so logica): confirmado bug no comportamento antigo (span desaparecia) e fix funcional (span e Session ID sobrevivem a multiplas trocas PT<->EN<->PT).' },
        { patch: 'UNIF-L4', build: '2026-06-22', desc: 'UNIFICACAO DE LOTES (Relatorio Pericial PERF-CRUZAMENTO-L1xL3-2026-06-22): Cruzamento forense cirurgico Lote1 x Lote3 executado por perito tecnico independente. Resolucao de regressao de codigo: 10 ficheiros promovidos ao estado F14 do Lote1 (script.js +34492b, unifed_triada_export.js +36085b, unifed_questionnaire_50questions.js +24247b com 250 strings EN-US, panel.html +417b patches F12/F15, nexus.js, translations.js, unifed_contraperiria_export.js, unifed_merkle_engine.js, index.html, unifed_architecture_report.js). Retencao da estrutura documental do Lote3 (4 documentos de entrega formal: MANIFESTO_INTEGRIDADE, MANIFESTO_CONFORMIDADE, RELATORIO_TECNICO, RESUMO_EXECUTIVO). Actualizacao de manifestos probatorios com Master Hash real recalculado. Conformidade D.L. n.o 28/2019 restabelecida.' }
    ])
});
console.log('[UNIFED-VERSION] ✅ Version manifest carregado:', window.UNIFED_VERSION.full);
